/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();

        jPanelIngreso.setVisible(true);
        jPanelRegistroFuncion.setVisible(false);
        jPanelFactura.setVisible(false);

        setearRadioGroup();
        setearComboBoxes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroupIngDisp = new javax.swing.ButtonGroup();
        jButtonGroupAnimado = new javax.swing.ButtonGroup();
        jButtonGroupSexo = new javax.swing.ButtonGroup();
        jPanelFondo = new javax.swing.JPanel();
        jPanelIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldIngresoNombre = new javax.swing.JTextField();
        jComboBoxIngresoPais = new javax.swing.JComboBox<>();
        jComboBoxIngresoGenero = new javax.swing.JComboBox<>();
        jComboBoxIngresoCal = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIngDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldIngAgno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonIngElenco = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonIngDispNo = new javax.swing.JRadioButton();
        jRadioButtonIngDispSi = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonIngCancel = new javax.swing.JButton();
        jButtonIngConfirmar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldIntFrameApellido = new javax.swing.JTextField();
        jTextFieldIntFrameRol = new javax.swing.JTextField();
        jButtonIntFrameCancelar = new javax.swing.JButton();
        jButtonIntFrameRegistrar = new javax.swing.JButton();
        jTextFieldIntFrameNombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jRadioButtonAnimadoNo = new javax.swing.JRadioButton();
        jRadioButtonAnimadoSi = new javax.swing.JRadioButton();
        jRadioButtonSexoF = new javax.swing.JRadioButton();
        jRadioButtonSexoM = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanelRegistroFuncion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxRegEstreno = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxRegSala = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxRegDia = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxRegHorario = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxRegCal = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonRegConfirmar = new javax.swing.JButton();
        jButtonRegCancel = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jComboBoxRegPelicula = new javax.swing.JComboBox<>();
        jPanelFactura = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelComprPelicula = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelComprSala = new javax.swing.JLabel();
        jLabelComprFechaVenta = new javax.swing.JLabel();
        jLabelComprCal = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelComprFechaFunc = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelComprHoraFunc = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabelComprVenaVia = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabelComprNroVenta = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabelComprPrecioEntrada = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabelComprNroEntradas = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabelComprImporteFinal = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cine");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setBackground(new java.awt.Color(60, 17, 17));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIngreso.setBackground(new java.awt.Color(60, 63, 64));
        jPanelIngreso.setForeground(new java.awt.Color(187, 187, 186));
        jPanelIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cine");
        jPanelIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 80));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingreso de Película");
        jPanelIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 570, -1));

        jLabel3.setBackground(new java.awt.Color(60, 63, 64));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione los datos");
        jPanelIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));
        jPanelIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 990, 10));

        jTextFieldIngresoNombre.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jTextFieldIngresoNombre.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIngresoNombre.setText("Nombre...");
        jTextFieldIngresoNombre.setToolTipText("Ingrese el nombre");
        jTextFieldIngresoNombre.setBorder(null);
        jTextFieldIngresoNombre.setCaretColor(new java.awt.Color(187, 187, 186));
        jTextFieldIngresoNombre.setDisabledTextColor(new java.awt.Color(153, 153, 152));
        jTextFieldIngresoNombre.setSelectedTextColor(new java.awt.Color(187, 187, 186));
        jTextFieldIngresoNombre.setSelectionColor(new java.awt.Color(75, 110, 174));
        jTextFieldIngresoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIngresoNombreFocusLost(evt);
            }
        });
        jTextFieldIngresoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIngresoNombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldIngresoNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldIngresoNombreMouseExited(evt);
            }
        });
        jTextFieldIngresoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresoNombreActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jTextFieldIngresoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        jComboBoxIngresoPais.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jComboBoxIngresoPais.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIngresoPais.setAutoscrolls(true);
        jComboBoxIngresoPais.setBorder(null);
        jComboBoxIngresoPais.setFocusable(false);
        jPanelIngreso.add(jComboBoxIngresoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 150, 30));

        jComboBoxIngresoGenero.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jComboBoxIngresoGenero.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIngresoGenero.setMaximumRowCount(7);
        jComboBoxIngresoGenero.setBorder(null);
        jComboBoxIngresoGenero.setFocusable(false);
        jComboBoxIngresoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIngresoGeneroActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jComboBoxIngresoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 150, 30));

        jComboBoxIngresoCal.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jComboBoxIngresoCal.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIngresoCal.setMaximumRowCount(5);
        jComboBoxIngresoCal.setBorder(null);
        jComboBoxIngresoCal.setFocusable(false);
        jPanelIngreso.add(jComboBoxIngresoCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 150, 30));
        jPanelIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 840, 10));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese los datos restantes");
        jPanelIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 254));
        jPanelIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 800, 10));

        jLabel5.setBackground(new java.awt.Color(60, 63, 64));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duración (min.)");
        jPanelIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        jTextFieldIngDuracion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jTextFieldIngDuracion.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIngDuracion.setBorder(null);
        jTextFieldIngDuracion.setDisabledTextColor(new java.awt.Color(153, 204, 255));
        jTextFieldIngDuracion.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIngDuracion.setSelectionColor(new java.awt.Color(75, 110, 174));
        jTextFieldIngDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldIngDuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldIngDuracionMouseExited(evt);
            }
        });
        jTextFieldIngDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngDuracionActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jTextFieldIngDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 100, 30));

        jLabel6.setBackground(new java.awt.Color(60, 63, 64));
        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Título original");
        jPanelIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, 30));

        jTextFieldTitulo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldTitulo.setBorder(null);
        jTextFieldTitulo.setDisabledTextColor(new java.awt.Color(153, 204, 255));
        jTextFieldTitulo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTitulo.setSelectionColor(new java.awt.Color(75, 110, 174));
        jTextFieldTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldTituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldTituloMouseExited(evt);
            }
        });
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 100, 30));

        jTextFieldIngAgno.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jTextFieldIngAgno.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldIngAgno.setBorder(null);
        jTextFieldIngAgno.setDisabledTextColor(new java.awt.Color(153, 204, 255));
        jTextFieldIngAgno.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIngAgno.setSelectionColor(new java.awt.Color(75, 110, 174));
        jTextFieldIngAgno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldIngAgnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldIngAgnoMouseExited(evt);
            }
        });
        jTextFieldIngAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngAgnoActionPerformed(evt);
            }
        });
        jPanelIngreso.add(jTextFieldIngAgno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, 30));

        jLabel7.setBackground(new java.awt.Color(60, 63, 64));
        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Año de estreno");
        jPanelIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 30));

        jLabel9.setBackground(new java.awt.Color(60, 63, 64));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Disponible");
        jPanelIngreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, 30));

        jButtonIngElenco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIngElenco.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jButtonIngElenco.setForeground(new java.awt.Color(187, 187, 186));
        jButtonIngElenco.setText("REGISTRAR");
        jButtonIngElenco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButtonIngElenco.setFocusPainted(false);
        jButtonIngElenco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngElencoMouseClicked(evt);
            }
        });
        jPanelIngreso.add(jButtonIngElenco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 100, 30));

        jLabel10.setBackground(new java.awt.Color(60, 63, 64));
        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registrar elenco");
        jPanelIngreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 30));

        jRadioButtonIngDispNo.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonIngDispNo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jRadioButtonIngDispNo.setForeground(new java.awt.Color(187, 187, 186));
        jRadioButtonIngDispNo.setText("No");
        jRadioButtonIngDispNo.setContentAreaFilled(false);
        jRadioButtonIngDispNo.setFocusPainted(false);
        jRadioButtonIngDispNo.setFocusable(false);
        jPanelIngreso.add(jRadioButtonIngDispNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jRadioButtonIngDispSi.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonIngDispSi.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jRadioButtonIngDispSi.setForeground(new java.awt.Color(187, 187, 186));
        jRadioButtonIngDispSi.setText("SI");
        jRadioButtonIngDispSi.setContentAreaFilled(false);
        jRadioButtonIngDispSi.setFocusPainted(false);
        jRadioButtonIngDispSi.setFocusable(false);
        jPanelIngreso.add(jRadioButtonIngDispSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));
        jPanelIngreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 990, 10));

        jButtonIngCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIngCancel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 21)); // NOI18N
        jButtonIngCancel.setForeground(new java.awt.Color(187, 187, 186));
        jButtonIngCancel.setText("Cancelar");
        jButtonIngCancel.setFocusPainted(false);
        jButtonIngCancel.setSelected(true);
        jButtonIngCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIngCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIngCancelMouseExited(evt);
            }
        });
        jPanelIngreso.add(jButtonIngCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 170, 40));

        jButtonIngConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIngConfirmar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 21)); // NOI18N
        jButtonIngConfirmar.setForeground(new java.awt.Color(187, 187, 186));
        jButtonIngConfirmar.setText("Confirmar");
        jButtonIngConfirmar.setFocusPainted(false);
        jButtonIngConfirmar.setSelected(true);
        jButtonIngConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIngConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIngConfirmarMouseExited(evt);
            }
        });
        jPanelIngreso.add(jButtonIngConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 170, 40));

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Ingresar Elenco");
        jInternalFrame1.setFocusTraversalPolicyProvider(true);
        jInternalFrame1.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(187, 187, 185));
        jPanel1.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIntFrameApellido.setBackground(new java.awt.Color(69, 73, 73));
        jTextFieldIntFrameApellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jTextFieldIntFrameApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldIntFrameApellido.setText("Apellido...");
        jTextFieldIntFrameApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIntFrameApellidoFocusLost(evt);
            }
        });
        jTextFieldIntFrameApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIntFrameApellidoMouseClicked(evt);
            }
        });
        jPanel1.add(jTextFieldIntFrameApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 167, 40));

        jTextFieldIntFrameRol.setBackground(new java.awt.Color(69, 73, 73));
        jTextFieldIntFrameRol.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jTextFieldIntFrameRol.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldIntFrameRol.setText("Rol...");
        jTextFieldIntFrameRol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIntFrameRolFocusLost(evt);
            }
        });
        jTextFieldIntFrameRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIntFrameRolMouseClicked(evt);
            }
        });
        jPanel1.add(jTextFieldIntFrameRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 167, 40));

        jButtonIntFrameCancelar.setBackground(new java.awt.Color(60, 63, 64));
        jButtonIntFrameCancelar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButtonIntFrameCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntFrameCancelar.setText("Listo");
        jButtonIntFrameCancelar.setFocusPainted(false);
        jButtonIntFrameCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonIntFrameCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIntFrameCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonIntFrameCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 100, 40));

        jButtonIntFrameRegistrar.setBackground(new java.awt.Color(60, 63, 64));
        jButtonIntFrameRegistrar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButtonIntFrameRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntFrameRegistrar.setText("Registrar");
        jButtonIntFrameRegistrar.setFocusPainted(false);
        jButtonIntFrameRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonIntFrameRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonIntFrameRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIntFrameRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonIntFrameRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 100, 40));

        jTextFieldIntFrameNombre.setBackground(new java.awt.Color(69, 73, 73));
        jTextFieldIntFrameNombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jTextFieldIntFrameNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldIntFrameNombre.setText("Nombre...");
        jTextFieldIntFrameNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIntFrameNombreFocusLost(evt);
            }
        });
        jTextFieldIntFrameNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIntFrameNombreMouseClicked(evt);
            }
        });
        jTextFieldIntFrameNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntFrameNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIntFrameNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 167, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Animado");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 20));

        jRadioButtonAnimadoNo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAnimadoNo.setText("No");
        jRadioButtonAnimadoNo.setFocusPainted(false);
        jRadioButtonAnimadoNo.setOpaque(false);
        jRadioButtonAnimadoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnimadoNoActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonAnimadoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jRadioButtonAnimadoSi.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAnimadoSi.setText("Si");
        jRadioButtonAnimadoSi.setFocusPainted(false);
        jRadioButtonAnimadoSi.setOpaque(false);
        jRadioButtonAnimadoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnimadoSiActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonAnimadoSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jRadioButtonSexoF.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSexoF.setText("F");
        jRadioButtonSexoF.setFocusPainted(false);
        jRadioButtonSexoF.setOpaque(false);
        jRadioButtonSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSexoFActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonSexoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jRadioButtonSexoM.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSexoM.setText("M");
        jRadioButtonSexoM.setFocusPainted(false);
        jRadioButtonSexoM.setOpaque(false);
        jRadioButtonSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSexoMActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonSexoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sexo");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 70, 20));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelIngreso.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 451, 220));
        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(168, 84, 0));
        kGradientPanel1.setkGradientFocus(80);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 33, 188));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelIngreso.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 610));

        jPanelFondo.add(jPanelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));
        jPanelIngreso.getAccessibleContext().setAccessibleName("");

        jPanelRegistroFuncion.setBackground(new java.awt.Color(60, 63, 64));
        jPanelRegistroFuncion.setForeground(new java.awt.Color(187, 187, 186));
        jPanelRegistroFuncion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Above DEMO", 1, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cine");
        jPanelRegistroFuncion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 80));

        jLabel11.setFont(new java.awt.Font("Raleway ExtraLight", 0, 65)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Registro de Función");
        jPanelRegistroFuncion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 600, -1));

        jLabel12.setBackground(new java.awt.Color(60, 63, 64));
        jLabel12.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seleccione los datos");
        jPanelRegistroFuncion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanelRegistroFuncion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 990, 10));

        jLabel13.setBackground(new java.awt.Color(60, 63, 64));
        jLabel13.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Película");
        jPanelRegistroFuncion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabel14.setBackground(new java.awt.Color(60, 63, 64));
        jLabel14.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("¡Estreno?");
        jPanelRegistroFuncion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        jComboBoxRegEstreno.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegEstreno.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegEstreno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-Estreno", "Esteno", "Cuando la pasan de nuevo" }));
        jComboBoxRegEstreno.setBorder(null);
        jComboBoxRegEstreno.setFocusable(false);
        jPanelRegistroFuncion.add(jComboBoxRegEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, 30));

        jLabel15.setBackground(new java.awt.Color(60, 63, 64));
        jLabel15.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sala");
        jPanelRegistroFuncion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        jComboBoxRegSala.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegSala.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRegSala.setBorder(null);
        jComboBoxRegSala.setFocusable(false);
        jPanelRegistroFuncion.add(jComboBoxRegSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, 30));

        jLabel16.setBackground(new java.awt.Color(60, 63, 64));
        jLabel16.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Día");
        jPanelRegistroFuncion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 30));

        jComboBoxRegDia.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegDia.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRegDia.setBorder(null);
        jComboBoxRegDia.setFocusable(false);
        jPanelRegistroFuncion.add(jComboBoxRegDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 150, 30));

        jLabel17.setBackground(new java.awt.Color(60, 63, 64));
        jLabel17.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horario");
        jPanelRegistroFuncion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 30));

        jComboBoxRegHorario.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegHorario.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRegHorario.setBorder(null);
        jComboBoxRegHorario.setFocusable(false);
        jPanelRegistroFuncion.add(jComboBoxRegHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 150, 30));

        jLabel18.setBackground(new java.awt.Color(60, 63, 64));
        jLabel18.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("calificación");
        jPanelRegistroFuncion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 30));

        jComboBoxRegCal.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegCal.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegCal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRegCal.setBorder(null);
        jComboBoxRegCal.setFocusable(false);
        jPanelRegistroFuncion.add(jComboBoxRegCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 150, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanelRegistroFuncion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 840, 10));

        jButtonRegConfirmar.setBackground(new java.awt.Color(60, 63, 64));
        jButtonRegConfirmar.setFont(new java.awt.Font("Panama Light", 1, 21)); // NOI18N
        jButtonRegConfirmar.setForeground(new java.awt.Color(187, 187, 186));
        jButtonRegConfirmar.setText("Confirmar");
        jButtonRegConfirmar.setFocusPainted(false);
        jButtonRegConfirmar.setSelected(true);
        jPanelRegistroFuncion.add(jButtonRegConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 170, 40));

        jButtonRegCancel.setBackground(new java.awt.Color(60, 63, 64));
        jButtonRegCancel.setFont(new java.awt.Font("Panama Light", 1, 21)); // NOI18N
        jButtonRegCancel.setForeground(new java.awt.Color(187, 187, 186));
        jButtonRegCancel.setText("Cancelar");
        jButtonRegCancel.setFocusPainted(false);
        jButtonRegCancel.setSelected(true);
        jPanelRegistroFuncion.add(jButtonRegCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 170, 40));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(137, 79, 0));
        kGradientPanel2.setkGradientFocus(80);
        kGradientPanel2.setkStartColor(new java.awt.Color(171, 235, 184));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxRegPelicula.setFont(new java.awt.Font("Panama Light", 1, 12)); // NOI18N
        jComboBoxRegPelicula.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRegPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRegPelicula.setBorder(null);
        jComboBoxRegPelicula.setFocusable(false);
        kGradientPanel2.add(jComboBoxRegPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 30));

        jPanelRegistroFuncion.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 600));

        jPanelFondo.add(jPanelRegistroFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 600));
        jPanelRegistroFuncion.getAccessibleContext().setAccessibleName("");

        jPanelFactura.setBackground(new java.awt.Color(60, 63, 64));
        jPanelFactura.setForeground(new java.awt.Color(187, 187, 186));
        jPanelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Raleway ExtraLight", 0, 65)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Comprobante");
        jPanelFactura.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 410, -1));

        jLabel22.setFont(new java.awt.Font("Above DEMO", 1, 80)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cine");
        jPanelFactura.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 80));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 10));

        jLabelComprPelicula.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprPelicula.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprPelicula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprPelicula.setText("A star is born");
        jPanelFactura.add(jLabelComprPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 100, 30));

        jLabel24.setBackground(new java.awt.Color(60, 63, 64));
        jLabel24.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Fecha de función");
        jPanelFactura.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 30));

        jLabel25.setBackground(new java.awt.Color(60, 63, 64));
        jLabel25.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Fecha de venta");
        jPanelFactura.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabelComprSala.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprSala.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprSala.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprSala.setText("2");
        jPanelFactura.add(jLabelComprSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 70, 30));

        jLabelComprFechaVenta.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprFechaVenta.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprFechaVenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprFechaVenta.setText("10/06/2019");
        jPanelFactura.add(jLabelComprFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 70, 30));

        jLabelComprCal.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprCal.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprCal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprCal.setText("excelente");
        jPanelFactura.add(jLabelComprCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 110, 30));

        jLabel29.setBackground(new java.awt.Color(60, 63, 64));
        jLabel29.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Película");
        jPanelFactura.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabelComprFechaFunc.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprFechaFunc.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprFechaFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprFechaFunc.setText("11/06/2019");
        jPanelFactura.add(jLabelComprFechaFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 70, 30));

        jLabel31.setBackground(new java.awt.Color(60, 63, 64));
        jLabel31.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("hora de función");
        jPanelFactura.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        jLabelComprHoraFunc.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprHoraFunc.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprHoraFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprHoraFunc.setText("18:56 ");
        jPanelFactura.add(jLabelComprHoraFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 30));

        jLabel33.setBackground(new java.awt.Color(60, 63, 64));
        jLabel33.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Sala");
        jPanelFactura.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        jLabel35.setBackground(new java.awt.Color(60, 63, 64));
        jLabel35.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("calificación");
        jPanelFactura.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 30));

        jLabel37.setBackground(new java.awt.Color(60, 63, 64));
        jLabel37.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Venta vía");
        jPanelFactura.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 30));

        jLabelComprVenaVia.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprVenaVia.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprVenaVia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprVenaVia.setText("boletería");
        jPanelFactura.add(jLabelComprVenaVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 130, 30));

        jLabel39.setBackground(new java.awt.Color(60, 63, 64));
        jLabel39.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("nro venta");
        jPanelFactura.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, 30));

        jLabelComprNroVenta.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprNroVenta.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprNroVenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprNroVenta.setText("198557");
        jPanelFactura.add(jLabelComprNroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 130, 30));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode3.png"))); // NOI18N
        jPanelFactura.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 210, 80));

        jLabel36.setBackground(new java.awt.Color(60, 63, 64));
        jLabel36.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("precio entrada");
        jPanelFactura.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 110, 30));

        jLabelComprPrecioEntrada.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprPrecioEntrada.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprPrecioEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprPrecioEntrada.setText("$200");
        jPanelFactura.add(jLabelComprPrecioEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 70, 30));

        jLabel42.setBackground(new java.awt.Color(60, 63, 64));
        jLabel42.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("nro entradas");
        jPanelFactura.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 110, 30));

        jLabelComprNroEntradas.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprNroEntradas.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprNroEntradas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprNroEntradas.setText("1");
        jPanelFactura.add(jLabelComprNroEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 70, 30));

        jLabel44.setBackground(new java.awt.Color(60, 63, 64));
        jLabel44.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("importe final");
        jPanelFactura.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 110, 30));

        jLabelComprImporteFinal.setBackground(new java.awt.Color(60, 63, 64));
        jLabelComprImporteFinal.setFont(new java.awt.Font("Panama Light", 0, 12)); // NOI18N
        jLabelComprImporteFinal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprImporteFinal.setText("$200");
        jPanelFactura.add(jLabelComprImporteFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 70, 30));
        jPanelFactura.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 600, 10));

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 10));

        jSeparator10.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, 10));

        jSeparator11.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 190, 10));

        jSeparator12.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, 10));

        jSeparator13.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 190, 10));

        jSeparator14.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 190, 10));

        jSeparator15.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFactura.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 190, 10));
        jPanelFactura.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 10));

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFactura.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 10, 110));

        jPanelFondo.add(jPanelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));
        jPanelFactura.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIntFrameCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIntFrameCancelarMouseClicked

        jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButtonIntFrameCancelarMouseClicked

    private void jButtonIngConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngConfirmarMouseClicked

        boolean key = saberSiEstaPelicula(jTextFieldIngresoNombre.getText());

        if (jTextFieldIngresoNombre.getText().isEmpty() || jComboBoxIngresoGenero.getSelectedItem().equals("Género") || jComboBoxIngresoCal.getSelectedItem().equals("Clasificación")
                || jComboBoxIngresoPais.getSelectedItem().equals("País Origen") || jTextFieldIngDuracion.getText().isEmpty() || jTextFieldTitulo.getText().isEmpty() || jTextFieldIngAgno.getText().isEmpty()
                || (!jRadioButtonIngDispSi.isSelected() && !jRadioButtonIngDispNo.isSelected()) || key) {

            if (key) {
                JOptionPane.showMessageDialog(null, "Ya existe una pelicula con ese nombre");
            } else {
                JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
            }

        } else {

            boolean disponible;
            Date fechaIngreso = new Date();
            PaisOrigen pais = new PaisOrigen();
            Genero genero = new Genero();
            Calificacion calificacion = new Calificacion();

            pais.setNombre((String) jComboBoxIngresoPais.getSelectedItem());

            genero.setNombre((String) jComboBoxIngresoGenero.getSelectedItem());

            calificacion.setNombre((String) jComboBoxIngresoCal.getSelectedItem());

            disponible = jRadioButtonIngDispSi.isSelected(); 

            peliculas.add(new Pelicula((Integer.parseInt(jTextFieldIngAgno.getText())), disponible,
                    Integer.parseInt(jTextFieldIngDuracion.getText()), fechaIngreso, jTextFieldIngresoNombre.getText(),
                    jTextFieldTitulo.getText(), pais, genero, calificacion, personajes, new java.util.ArrayList<>())
            );

            JOptionPane.showMessageDialog(null, "Película ingresada con éxito");
            limpiarCampos();

            for (Pelicula p : peliculas) {
                mostrarPeliculaConsola(p);
            }
        }
    }//GEN-LAST:event_jButtonIngConfirmarMouseClicked

    private void limpiarCampos() {
        jTextFieldIngresoNombre.setText("Nombre...");
        jComboBoxIngresoGenero.setSelectedItem("Género");
        jComboBoxIngresoCal.setSelectedItem("Clasificación");
        jComboBoxIngresoPais.setSelectedItem("País Origen");
        jTextFieldIngDuracion.setText("");
        jTextFieldTitulo.setText("");
        jTextFieldIngAgno.setText("");
        jButtonGroupIngDisp.clearSelection();
    }

    private void jButtonIngElencoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngElencoMouseClicked
        jInternalFrame1.setVisible(true);

    }//GEN-LAST:event_jButtonIngElencoMouseClicked

    private void jTextFieldIngAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngAgnoActionPerformed
        System.out.println("" + jTextFieldIngAgno.getText());
    }//GEN-LAST:event_jTextFieldIngAgnoActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        System.out.println("" + jTextFieldTitulo.getText());
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldIngDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngDuracionActionPerformed
        System.out.println("" + jTextFieldIngDuracion.getText());
        int i;
        try {
            i = Integer.parseInt(jTextFieldIngDuracion.getText());
        } catch (NumberFormatException e) {
            i = 0;
        }
        System.out.println(" entero -.>> " + i);

    }//GEN-LAST:event_jTextFieldIngDuracionActionPerformed

    private void jComboBoxIngresoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIngresoGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIngresoGeneroActionPerformed

    private void jTextFieldIngresoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresoNombreActionPerformed
        System.out.println("" + jTextFieldIngresoNombre.getText());

    }//GEN-LAST:event_jTextFieldIngresoNombreActionPerformed

    private void resaltaBordeFondo(JComponent comp, Color c, Color c2) {
        comp.setBorder(BorderFactory.createLineBorder(c, 2));
        comp.setBackground(c2);
    }

    private void jButtonIngCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngCancelMouseEntered

        resaltaBordeFondo(jButtonIngCancel, new Color(80, 0, 0), new Color(80, 0, 0));
    }//GEN-LAST:event_jButtonIngCancelMouseEntered

    private void jButtonIngCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngCancelMouseExited
        resaltaBordeFondo(jButtonIngCancel, new Color(102, 51, 0), new Color(255, 255, 255));

    }//GEN-LAST:event_jButtonIngCancelMouseExited

    private void jButtonIngConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngConfirmarMouseEntered
        resaltaBordeFondo(jButtonIngConfirmar, new Color(0, 80, 0), new Color(0, 80, 0));
    }//GEN-LAST:event_jButtonIngConfirmarMouseEntered

    private void jButtonIngConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngConfirmarMouseExited
        resaltaBordeFondo(jButtonIngConfirmar, new Color(102, 51, 0), new Color(255, 255, 255));

    }//GEN-LAST:event_jButtonIngConfirmarMouseExited

    private void jTextFieldIngresoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresoNombreMouseClicked
        if (jTextFieldIngresoNombre.getText().equals("Nombre...")) {
            jTextFieldIngresoNombre.setText("");
        }

    }//GEN-LAST:event_jTextFieldIngresoNombreMouseClicked

    private void jButtonIntFrameRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIntFrameRegistrarMouseClicked
        boolean an;
        String sexo;

        if (jRadioButtonAnimadoSi.isSelected()) {
            an = true;
        } else {
            an = false;
        }

        if (jRadioButtonSexoM.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }

        Actor actor = new Actor(an, jTextFieldIntFrameNombre.getText(), jTextFieldIntFrameApellido.getText(), new Sexo(sexo));

        Personaje p = new Personaje(actor, new Rol(jTextFieldIntFrameRol.getText()));

        personajes.add(p);

        jTextFieldIntFrameNombre.setText("Nombre...");
        jTextFieldIntFrameApellido.setText("Apellido...");
        jTextFieldIntFrameRol.setText("Rol...");

        jButtonGroupAnimado.clearSelection();
        jButtonGroupSexo.clearSelection();


    }//GEN-LAST:event_jButtonIntFrameRegistrarMouseClicked

    private void jTextFieldIngDuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngDuracionMouseEntered
        resaltarBorde(jTextFieldIngDuracion, new java.awt.Color(153, 76, 0));

    }//GEN-LAST:event_jTextFieldIngDuracionMouseEntered

    private void jTextFieldIngDuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngDuracionMouseExited
        resaltarBorde(jTextFieldIngDuracion, new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jTextFieldIngDuracionMouseExited

    private void jTextFieldIngresoNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresoNombreMouseEntered
        resaltarBorde(jTextFieldIngresoNombre, new java.awt.Color(153, 76, 0));
    }//GEN-LAST:event_jTextFieldIngresoNombreMouseEntered

    private void jTextFieldIngresoNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresoNombreMouseExited
        resaltarBorde(jTextFieldIngresoNombre, new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jTextFieldIngresoNombreMouseExited

    private void jTextFieldTituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTituloMouseEntered
        resaltarBorde(jTextFieldTitulo, new java.awt.Color(153, 76, 0));
    }//GEN-LAST:event_jTextFieldTituloMouseEntered

    private void jTextFieldTituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTituloMouseExited
        resaltarBorde(jTextFieldTitulo, new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jTextFieldTituloMouseExited

    private void jTextFieldIngAgnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngAgnoMouseEntered
        resaltarBorde(jTextFieldIngAgno, new java.awt.Color(153, 76, 0));
    }//GEN-LAST:event_jTextFieldIngAgnoMouseEntered

    private void jTextFieldIngAgnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngAgnoMouseExited
        resaltarBorde(jTextFieldIngAgno, new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jTextFieldIngAgnoMouseExited

    private void jTextFieldIntFrameApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameApellidoMouseClicked
        cambiarTextoJTextField(jTextFieldIntFrameApellido, jTextFieldIntFrameApellido.getText());
    }//GEN-LAST:event_jTextFieldIntFrameApellidoMouseClicked

    private void jTextFieldIntFrameRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameRolMouseClicked
        cambiarTextoJTextField(jTextFieldIntFrameRol, jTextFieldIntFrameRol.getText());
    }//GEN-LAST:event_jTextFieldIntFrameRolMouseClicked

    private void jTextFieldIntFrameNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameNombreMouseClicked
        cambiarTextoJTextField(jTextFieldIntFrameNombre, jTextFieldIntFrameNombre.getText());
    }//GEN-LAST:event_jTextFieldIntFrameNombreMouseClicked

    private void cambiarTextoJTextField(javax.swing.JTextField jt, String campo) {
        if (jt.getText().equals(campo)) {
            jt.setText("");
        } else if (jt.getText().equals("")) {
            jt.setText(campo);
        }
    }

    private void jTextFieldIntFrameNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntFrameNombreActionPerformed

    private void jRadioButtonAnimadoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnimadoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAnimadoNoActionPerformed

    private void jRadioButtonAnimadoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnimadoSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAnimadoSiActionPerformed

    private void jRadioButtonSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSexoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSexoFActionPerformed

    private void jRadioButtonSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSexoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSexoMActionPerformed

    private void jTextFieldIntFrameNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameNombreFocusLost
        cambiarTextoJTextField(jTextFieldIntFrameNombre, "Nombre...");
    }//GEN-LAST:event_jTextFieldIntFrameNombreFocusLost

    private void jTextFieldIntFrameApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameApellidoFocusLost
        cambiarTextoJTextField(jTextFieldIntFrameApellido, "Apellido...");
    }//GEN-LAST:event_jTextFieldIntFrameApellidoFocusLost

    private void jTextFieldIntFrameRolFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIntFrameRolFocusLost
        cambiarTextoJTextField(jTextFieldIntFrameRol, "Rol...");
    }//GEN-LAST:event_jTextFieldIntFrameRolFocusLost

    private void jTextFieldIngresoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIngresoNombreFocusLost
        cambiarTextoJTextField(jTextFieldIngresoNombre, "Nombre...");


    }//GEN-LAST:event_jTextFieldIngresoNombreFocusLost

    private void jButtonIngCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonIngCancelMouseClicked

    private void resaltarBorde(javax.swing.JComponent comp, java.awt.Color c) {
        comp.setBorder(javax.swing.BorderFactory.createLineBorder(c, 3));
    }

    private boolean saberSiEstaPelicula(String s) {
        for (Pelicula p : peliculas) {
            if (p.getNombre().equals(s)) {
                return true;
            }
        }
        return false;
    }

    private void setearComboBoxes() {

        ArrayList<PaisOrigen> paises = new ArrayList<>();
        ArrayList<Genero> generos = new ArrayList<>();
        ArrayList<Calificacion> cal = new ArrayList<>();

        jComboBoxIngresoPais.addItem("País Origen");
        jComboBoxIngresoGenero.addItem("Género");
        jComboBoxIngresoCal.addItem("Clasificación");

        paises.add(new PaisOrigen("Español", "Argentina"));
        paises.add(new PaisOrigen("Portugués", "Brasil"));
        paises.add(new PaisOrigen("Español", "Chile"));
        paises.add(new PaisOrigen("Español", "Colombia"));
        paises.add(new PaisOrigen("Español", "España"));
        paises.add(new PaisOrigen("Inglés", "Estados Unidos"));
        paises.add(new PaisOrigen("Francés", "Francia"));
        paises.add(new PaisOrigen("Inglés", "Inglaterra"));
        paises.add(new PaisOrigen("Italiano", "Italia"));
        paises.add(new PaisOrigen("Español", "Mexico"));
        paises.add(new PaisOrigen("Portugués", "Portugal"));
        paises.add(new PaisOrigen("Español", "Uruguay"));

        generos.add(new Genero(1, "Drama"));
        generos.add(new Genero(2, "Comedia"));
        generos.add(new Genero(3, "Terror"));
        generos.add(new Genero(4, "Acción"));
        generos.add(new Genero(5, "Suspenso"));
        generos.add(new Genero(6, "Ciencia Ficción"));

        cal.add(new Calificacion("ATP", 1));
        cal.add(new Calificacion("+13", 2));
        cal.add(new Calificacion("+16", 3));
        cal.add(new Calificacion("+18", 4));

        for (PaisOrigen p : paises) {
            jComboBoxIngresoPais.addItem(p.getNombre());
        }

        for (Genero g : generos) {
            jComboBoxIngresoGenero.addItem(g.getNombre());
        }

        for (Calificacion f : cal) {
            jComboBoxIngresoCal.addItem(f.getNombre());
        }

    }

    private void setearRadioGroup() {
        jButtonGroupIngDisp.add(jRadioButtonIngDispNo);
        jButtonGroupIngDisp.add(jRadioButtonIngDispSi);

        jButtonGroupAnimado.add(jRadioButtonAnimadoSi);
        jButtonGroupAnimado.add(jRadioButtonAnimadoNo);

        jButtonGroupSexo.add(jRadioButtonSexoM);
        jButtonGroupSexo.add(jRadioButtonSexoF);
    }

    //METODO DE PRUEBA EN CONSOLA DESPUES DE CREADA LA PELICULA
    private void mostrarPeliculaConsola(Pelicula p) {
        System.out.println("Nombre: " + p.getNombre() + "\nTitulo Original: " + p.getTituloOriginal() + "\nAño: " + p.getAgnoEstreno()
                + "\nFecha " + p.getFechaIngreso() + "\nDuracion " + p.getDuracion() + "\nDisponible " + p.estaDisponible() + "\nPais: "
                + p.getPais().getNombre() + "\nGenero " + p.getGenero().getNombre()
                + "\nCalificacion: " + p.getCalificacion().getNombre() + "\nFunciones: " + p.getFunciones().toString());

        for (Personaje i : p.getPersonajes()) {
            System.out.println("" + i.getActor().getApellido() + ", " + i.getActor().getNombre());
        }

        System.out.println("<------------------------------------>\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    //<------------------------------------------------------------------------
    private java.util.ArrayList<Personaje> personajes = new java.util.ArrayList<>();
    private java.util.ArrayList<Pelicula> peliculas = new java.util.ArrayList<>();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jButtonGroupAnimado;
    private javax.swing.ButtonGroup jButtonGroupIngDisp;
    private javax.swing.ButtonGroup jButtonGroupSexo;
    private javax.swing.JButton jButtonIngCancel;
    private javax.swing.JButton jButtonIngConfirmar;
    private javax.swing.JButton jButtonIngElenco;
    private javax.swing.JButton jButtonIntFrameCancelar;
    private javax.swing.JButton jButtonIntFrameRegistrar;
    private javax.swing.JButton jButtonRegCancel;
    private javax.swing.JButton jButtonRegConfirmar;
    private javax.swing.JComboBox<String> jComboBoxIngresoCal;
    private javax.swing.JComboBox<String> jComboBoxIngresoGenero;
    private javax.swing.JComboBox<String> jComboBoxIngresoPais;
    private javax.swing.JComboBox<String> jComboBoxRegCal;
    private javax.swing.JComboBox<String> jComboBoxRegDia;
    private javax.swing.JComboBox<String> jComboBoxRegEstreno;
    private javax.swing.JComboBox<String> jComboBoxRegHorario;
    private javax.swing.JComboBox<String> jComboBoxRegPelicula;
    private javax.swing.JComboBox<String> jComboBoxRegSala;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelComprCal;
    private javax.swing.JLabel jLabelComprFechaFunc;
    private javax.swing.JLabel jLabelComprFechaVenta;
    private javax.swing.JLabel jLabelComprHoraFunc;
    private javax.swing.JLabel jLabelComprImporteFinal;
    private javax.swing.JLabel jLabelComprNroEntradas;
    private javax.swing.JLabel jLabelComprNroVenta;
    private javax.swing.JLabel jLabelComprPelicula;
    private javax.swing.JLabel jLabelComprPrecioEntrada;
    private javax.swing.JLabel jLabelComprSala;
    private javax.swing.JLabel jLabelComprVenaVia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelIngreso;
    private javax.swing.JPanel jPanelRegistroFuncion;
    private javax.swing.JRadioButton jRadioButtonAnimadoNo;
    private javax.swing.JRadioButton jRadioButtonAnimadoSi;
    private javax.swing.JRadioButton jRadioButtonIngDispNo;
    private javax.swing.JRadioButton jRadioButtonIngDispSi;
    private javax.swing.JRadioButton jRadioButtonSexoF;
    private javax.swing.JRadioButton jRadioButtonSexoM;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldIngAgno;
    private javax.swing.JTextField jTextFieldIngDuracion;
    private javax.swing.JTextField jTextFieldIngresoNombre;
    private javax.swing.JTextField jTextFieldIntFrameApellido;
    private javax.swing.JTextField jTextFieldIntFrameNombre;
    private javax.swing.JTextField jTextFieldIntFrameRol;
    private javax.swing.JTextField jTextFieldTitulo;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
